use std::fs;
use std::path::{Path, PathBuf};
use std::{env, str};

const WEBOTS_LINUX_PATH: &str = "/usr/local/webots";
const WEBOTS_MACOS_PATH: &str = "/Applications/Webots.app/Contents";
const WEBOTS_WINDOWS_PATH: &str = "C:\\Program Files\\Webots";
const ENV_WEBOTS_HOME: &str = "WEBOTS_HOME";
const ENV_WEBOTS_LINK: &str = "WEBOTS_LINK";
fn feature_env_to_version(feature: &str) -> Option<String> {
    let version = feature.strip_prefix("CARGO_FEATURE_V")?;
    Some(format!("v{}", version.to_ascii_lowercase().replace('_', "")))
}

fn selected_bindings_version() -> Result<String, Box<dyn std::error::Error>> {
    let enabled: Vec<_> = env::vars()
        .filter_map(|(name, _)| feature_env_to_version(&name))
        .collect();

    match enabled.as_slice() {
        [version] => Ok(version.clone()),
        [] => Err("No Webots bindings version feature enabled.".into()),
        _ => Err("Multiple Webots bindings version features enabled at once.".into()),
    }
}

fn wrapper_header_path(version: &str) -> PathBuf {
    Path::new("headers")
        .join(version.trim_start_matches('v'))
        .join("wrapper.h")
}

fn version_module_name(version: &str) -> String {
    version.to_string()
}

fn bindings_source_path(version: &str) -> PathBuf {
    Path::new("src")
        .join(version_module_name(version))
        .join("bindings.rs")
}

fn copy_directory_recursively(
    source: &Path,
    destination: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    if !destination.exists() {
        fs::create_dir_all(destination)?;
    }

    for entry in fs::read_dir(source)? {
        let entry = entry?;
        let entry_path = entry.path();
        let destination_path = destination.join(entry.file_name());
        let metadata = entry.metadata()?;

        if metadata.is_dir() {
            copy_directory_recursively(&entry_path, &destination_path)?;
        } else {
            fs::copy(&entry_path, &destination_path)?;
        }
    }

    Ok(())
}

fn generate_stub_bindings(
    bindings_src_path: &Path,
    stub_path: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    let source = fs::read_to_string(bindings_src_path)?;
    let mut stubs = String::from("// @generated by build.rs\n\n");

    let mut current_declaration: Option<String> = None;

    for line in source.lines() {
        let trimmed = line.trim();

        if current_declaration.is_none()
            && (trimmed.starts_with("pub fn wb_") || trimmed.starts_with("pub fn wbu_"))
        {
            current_declaration = Some(trimmed.to_string());
        } else if let Some(declaration) = &mut current_declaration {
            declaration.push(' ');
            declaration.push_str(trimmed);
        }

        let Some(declaration) = current_declaration.as_ref() else {
            continue;
        };

        if !declaration.ends_with(';') {
            continue;
        }

        let declaration = current_declaration.take().unwrap();
        let declaration = declaration.trim_end_matches(';');
        let signature = declaration
            .strip_prefix("pub fn ")
            .ok_or("Unexpected binding declaration format")?;
        let open_paren = signature.find('(').ok_or("Missing opening parenthesis")?;
        let close_paren = signature.rfind(')').ok_or("Missing closing parenthesis")?;
        let fn_name = &signature[..open_paren];
        let params = &signature[open_paren + 1..close_paren];
        let return_type = signature[close_paren + 1..]
            .trim()
            .strip_prefix("->")
            .map(str::trim);

        stubs.push_str("#[no_mangle]\n");
        stubs.push_str("#[allow(unused_variables, non_snake_case)]\n");
        stubs.push_str("pub unsafe extern \"C\" fn ");
        stubs.push_str(fn_name);
        stubs.push('(');
        stubs.push_str(params);
        stubs.push(')');

        if let Some(return_type) = return_type {
            stubs.push_str(" -> ");
            stubs.push_str(return_type);
            stubs.push_str(" {\n    unsafe { ::std::mem::zeroed() }\n}\n\n");
        } else {
            stubs.push_str(" {}\n\n");
        }
    }

    fs::write(stub_path, stubs)?;

    Ok(())
}

fn get_webots_path() -> Option<String> {
    if let Ok(path) = env::var(ENV_WEBOTS_HOME) {
        if Path::new(&path).exists() {
            return Some(path);
        }
    }

    let default_path = if cfg!(target_os = "linux") {
        WEBOTS_LINUX_PATH
    } else if cfg!(target_os = "macos") {
        WEBOTS_MACOS_PATH
    } else if cfg!(target_os = "windows") {
        WEBOTS_WINDOWS_PATH
    } else {
        return None;
    };

    Path::new(default_path)
        .exists()
        .then(|| default_path.to_string())
}

fn setup_webots_linking(webots_path: &str) -> Result<(), Box<dyn std::error::Error>> {
    let mut resolved_path = PathBuf::from(webots_path);
    let mut lib_path = resolved_path.join("lib/controller");

    if !lib_path.exists() && cfg!(target_os = "macos") {
        let contents_path = resolved_path.join("Contents");
        let contents_lib_path = contents_path.join("lib/controller");

        if contents_lib_path.exists() {
            resolved_path = contents_path;
            lib_path = contents_lib_path;
        }
    }

    if !lib_path.exists() {
        return Err(format!(
            "Webots controller library not found at {}",
            lib_path.display()
        )
        .into());
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR")?);
    fs::create_dir_all(&out_dir)?;

    let staging_root = out_dir.join("webots-runtime");
    if staging_root.exists() {
        fs::remove_dir_all(&staging_root)?;
    }

    let staged_controller_dir = if cfg!(target_os = "macos") {
        let target = staging_root.join("Contents").join("lib/controller");
        copy_directory_recursively(&lib_path, &target)?;
        target
    } else {
        let target = staging_root.join("lib/controller");
        copy_directory_recursively(&lib_path, &target)?;
        target
    };

    println!(
        "cargo:rustc-link-search={}",
        staged_controller_dir.display()
    );
    println!("cargo:rustc-link-lib=Controller");

    let target_profile_dir = out_dir
        .parent()
        .and_then(|path| path.parent())
        .and_then(|path| path.parent())
        .ok_or("Unable to determine Cargo target directory")?
        .to_path_buf();

    let relative_controller_path = staged_controller_dir
        .strip_prefix(&target_profile_dir)
        .ok()
        .map(|path| path.to_path_buf());

    if cfg!(target_os = "linux") {
        if let Some(relative_path) = &relative_controller_path {
            println!(
                "cargo:rustc-link-arg=-Wl,-rpath,$ORIGIN/{}",
                relative_path.to_string_lossy()
            );
        }

        println!(
            "cargo:rustc-link-arg=-Wl,-rpath,{}",
            staged_controller_dir.display()
        );
    } else if cfg!(target_os = "macos") {
        let staged_bundle_root = staging_root.join("Contents");

        if let Ok(relative_path) = staged_bundle_root.strip_prefix(&target_profile_dir) {
            println!(
                "cargo:rustc-link-arg=-Wl,-rpath,@loader_path/{}",
                relative_path.to_string_lossy()
            );
        }

        println!(
            "cargo:rustc-link-arg=-Wl,-rpath,{}",
            staged_bundle_root.display()
        );
    } else if cfg!(target_os = "windows") {
        let existing_path = env::var("PATH").unwrap_or_default();
        let staged_path = staged_controller_dir.to_string_lossy();
        let new_path = if existing_path.is_empty() {
            staged_path.to_string()
        } else {
            format!("{};{}", staged_path, existing_path)
        };

        println!("cargo:rustc-env=PATH={}", new_path);
    }

    println!(
        "cargo:warning=Linking Webots runtime from {}",
        resolved_path.display()
    );

    Ok(())
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("cargo:rerun-if-env-changed={}", ENV_WEBOTS_HOME);
    println!("cargo:rerun-if-env-changed={}", ENV_WEBOTS_LINK);
    println!("cargo:rustc-check-cfg=cfg(webots_runtime_linked)");
    println!("cargo:rustc-check-cfg=cfg(webots_api_version)");

    let bindings_version = selected_bindings_version()?;
    let bindings_src_path = bindings_source_path(&bindings_version);
    let wrapper_header_path = wrapper_header_path(&bindings_version);
    let out_dir = PathBuf::from(env::var("OUT_DIR")?);
    let stub_bindings_path = out_dir.join("bindings_stubs.rs");

    println!("cargo:rerun-if-changed={}", bindings_src_path.display());
    println!("cargo:rerun-if-changed={}", wrapper_header_path.display());
    println!("cargo:rustc-cfg=webots_api_version=\"{}\"", bindings_version);

    if !bindings_src_path.exists() {
        return Err(format!(
            "Checked-in bindings file not found: {}. Regenerate it with the bindings-generator crate.",
            bindings_src_path.display()
        )
        .into());
    }

    if !wrapper_header_path.exists() {
        return Err(format!(
            "Versioned wrapper header not found: {}",
            wrapper_header_path.display()
        )
        .into());
    }

    let should_link = env::var("CARGO_FEATURE_RUNTIME_LINK").is_ok()
        || matches!(env::var(ENV_WEBOTS_LINK).as_deref(), Ok("1"));

    if should_link {
        let webots_path = get_webots_path().ok_or(
            "Webots runtime linking was requested but no installation was found in the default location.",
        )?;
        setup_webots_linking(&webots_path)?;
        println!("cargo:rustc-cfg=webots_runtime_linked");
    } else {
        generate_stub_bindings(&bindings_src_path, &stub_bindings_path)?;
        println!(
            "cargo:warning=Using checked-in Webots bindings with autogenerated stubs; native runtime linking is disabled"
        );
    }

    Ok(())
}
