/* automatically generated by rust-bindgen 0.72.1 */

#![allow(dead_code, non_camel_case_types, non_snake_case, non_upper_case_globals)]

pub type WbDeviceTag = ::std::os::raw::c_ushort;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct WbImageStructPrivate {
    _unused: [u8; 0],
}
pub type WbImageRef = *mut WbImageStructPrivate;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct WbMotionStructPrivate {
    _unused: [u8; 0],
}
pub type WbMotionRef = *mut WbMotionStructPrivate;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct WbNodeStructPrivate {
    _unused: [u8; 0],
}
pub type WbNodeRef = *mut WbNodeStructPrivate;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct WbProtoInfoStructPrivate {
    _unused: [u8; 0],
}
pub type WbProtoRef = *mut WbProtoInfoStructPrivate;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct WbFieldStructPrivate {
    _unused: [u8; 0],
}
pub type WbFieldRef = *mut WbFieldStructPrivate;
pub const WbJointType_WB_ROTATIONAL: WbJointType = 0;
pub const WbJointType_WB_LINEAR: WbJointType = 1;
pub type WbJointType = ::std::os::raw::c_uint;
unsafe extern "C" {
    pub fn wb_accelerometer_enable(tag: WbDeviceTag, sampling_period: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_accelerometer_disable(tag: WbDeviceTag);
}
unsafe extern "C" {
    pub fn wb_accelerometer_get_sampling_period(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_accelerometer_get_lookup_table_size(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_accelerometer_get_lookup_table(tag: WbDeviceTag) -> *const f64;
}
unsafe extern "C" {
    pub fn wb_accelerometer_get_values(tag: WbDeviceTag) -> *const f64;
}
unsafe extern "C" {
    pub fn wb_altimeter_enable(tag: WbDeviceTag, sampling_period: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_altimeter_disable(tag: WbDeviceTag);
}
unsafe extern "C" {
    pub fn wb_altimeter_get_sampling_period(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_altimeter_get_value(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_brake_set_damping_constant(tag: WbDeviceTag, damping_constant: f64);
}
unsafe extern "C" {
    pub fn wb_brake_get_type(tag: WbDeviceTag) -> WbJointType;
}
unsafe extern "C" {
    pub fn wb_brake_get_motor(tag: WbDeviceTag) -> WbDeviceTag;
}
unsafe extern "C" {
    pub fn wb_brake_get_position_sensor(tag: WbDeviceTag) -> WbDeviceTag;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct WbCameraRecognitionObject {
    pub id: ::std::os::raw::c_int,
    pub position: [f64; 3usize],
    pub orientation: [f64; 4usize],
    pub size: [f64; 2usize],
    pub position_on_image: [::std::os::raw::c_int; 2usize],
    pub size_on_image: [::std::os::raw::c_int; 2usize],
    pub number_of_colors: ::std::os::raw::c_int,
    pub colors: *mut f64,
    pub model: *mut ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of WbCameraRecognitionObject"]
        [::std::mem::size_of::<WbCameraRecognitionObject>() - 120usize];
    ["Alignment of WbCameraRecognitionObject"]
        [::std::mem::align_of::<WbCameraRecognitionObject>() - 8usize];
    ["Offset of field: WbCameraRecognitionObject::id"]
        [::std::mem::offset_of!(WbCameraRecognitionObject, id) - 0usize];
    ["Offset of field: WbCameraRecognitionObject::position"]
        [::std::mem::offset_of!(WbCameraRecognitionObject, position) - 8usize];
    ["Offset of field: WbCameraRecognitionObject::orientation"]
        [::std::mem::offset_of!(WbCameraRecognitionObject, orientation) - 32usize];
    ["Offset of field: WbCameraRecognitionObject::size"]
        [::std::mem::offset_of!(WbCameraRecognitionObject, size) - 64usize];
    ["Offset of field: WbCameraRecognitionObject::position_on_image"]
        [::std::mem::offset_of!(WbCameraRecognitionObject, position_on_image) - 80usize];
    ["Offset of field: WbCameraRecognitionObject::size_on_image"]
        [::std::mem::offset_of!(WbCameraRecognitionObject, size_on_image) - 88usize];
    ["Offset of field: WbCameraRecognitionObject::number_of_colors"]
        [::std::mem::offset_of!(WbCameraRecognitionObject, number_of_colors) - 96usize];
    ["Offset of field: WbCameraRecognitionObject::colors"]
        [::std::mem::offset_of!(WbCameraRecognitionObject, colors) - 104usize];
    ["Offset of field: WbCameraRecognitionObject::model"]
        [::std::mem::offset_of!(WbCameraRecognitionObject, model) - 112usize];
};
unsafe extern "C" {
    pub fn wb_camera_enable(tag: WbDeviceTag, sampling_period: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_camera_disable(tag: WbDeviceTag);
}
unsafe extern "C" {
    pub fn wb_camera_get_sampling_period(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_camera_get_image(tag: WbDeviceTag) -> *const ::std::os::raw::c_uchar;
}
unsafe extern "C" {
    pub fn wb_camera_get_width(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_camera_get_height(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_camera_get_fov(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_camera_get_max_fov(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_camera_get_min_fov(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_camera_set_fov(tag: WbDeviceTag, fov: f64);
}
unsafe extern "C" {
    pub fn wb_camera_get_exposure(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_camera_set_exposure(tag: WbDeviceTag, exposure: f64);
}
unsafe extern "C" {
    pub fn wb_camera_get_focal_length(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_camera_get_focal_distance(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_camera_get_max_focal_distance(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_camera_get_min_focal_distance(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_camera_set_focal_distance(tag: WbDeviceTag, focal_distance: f64);
}
unsafe extern "C" {
    pub fn wb_camera_get_near(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_camera_save_image(
        tag: WbDeviceTag,
        filename: *const ::std::os::raw::c_char,
        quality: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_camera_has_recognition(tag: WbDeviceTag) -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_camera_recognition_enable(tag: WbDeviceTag, sampling_period: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_camera_recognition_disable(tag: WbDeviceTag);
}
unsafe extern "C" {
    pub fn wb_camera_recognition_get_sampling_period(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_camera_recognition_get_number_of_objects(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_camera_recognition_get_objects(tag: WbDeviceTag) -> *const WbCameraRecognitionObject;
}
unsafe extern "C" {
    pub fn wb_camera_recognition_has_segmentation(tag: WbDeviceTag) -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_camera_recognition_enable_segmentation(tag: WbDeviceTag);
}
unsafe extern "C" {
    pub fn wb_camera_recognition_disable_segmentation(tag: WbDeviceTag);
}
unsafe extern "C" {
    pub fn wb_camera_recognition_is_segmentation_enabled(
        tag: WbDeviceTag,
    ) -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_camera_recognition_get_segmentation_image(
        tag: WbDeviceTag,
    ) -> *const ::std::os::raw::c_uchar;
}
unsafe extern "C" {
    pub fn wb_camera_recognition_save_segmentation_image(
        tag: WbDeviceTag,
        filename: *const ::std::os::raw::c_char,
        quality: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_compass_enable(tag: WbDeviceTag, sampling_period: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_compass_disable(tag: WbDeviceTag);
}
unsafe extern "C" {
    pub fn wb_compass_get_sampling_period(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_compass_get_lookup_table_size(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_compass_get_lookup_table(tag: WbDeviceTag) -> *const f64;
}
unsafe extern "C" {
    pub fn wb_compass_get_values(tag: WbDeviceTag) -> *const f64;
}
unsafe extern "C" {
    pub fn wb_connector_enable_presence(tag: WbDeviceTag, sampling_period: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_connector_disable_presence(tag: WbDeviceTag);
}
unsafe extern "C" {
    pub fn wb_connector_get_presence_sampling_period(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_connector_get_presence(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_connector_lock(tag: WbDeviceTag);
}
unsafe extern "C" {
    pub fn wb_connector_unlock(tag: WbDeviceTag);
}
unsafe extern "C" {
    pub fn wb_connector_is_locked(tag: WbDeviceTag) -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_console_print(text: *const ::std::os::raw::c_char, stream: ::std::os::raw::c_int);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct WbContactPoint {
    pub point: [f64; 3usize],
    pub node_id: ::std::os::raw::c_int,
    pub padding: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of WbContactPoint"][::std::mem::size_of::<WbContactPoint>() - 32usize];
    ["Alignment of WbContactPoint"][::std::mem::align_of::<WbContactPoint>() - 8usize];
    ["Offset of field: WbContactPoint::point"]
        [::std::mem::offset_of!(WbContactPoint, point) - 0usize];
    ["Offset of field: WbContactPoint::node_id"]
        [::std::mem::offset_of!(WbContactPoint, node_id) - 24usize];
    ["Offset of field: WbContactPoint::padding"]
        [::std::mem::offset_of!(WbContactPoint, padding) - 28usize];
};
pub const WbNodeType_WB_NODE_NO_NODE: WbNodeType = 0;
pub const WbNodeType_WB_NODE_APPEARANCE: WbNodeType = 1;
pub const WbNodeType_WB_NODE_BACKGROUND: WbNodeType = 2;
pub const WbNodeType_WB_NODE_BILLBOARD: WbNodeType = 3;
pub const WbNodeType_WB_NODE_BOX: WbNodeType = 4;
pub const WbNodeType_WB_NODE_CAD_SHAPE: WbNodeType = 5;
pub const WbNodeType_WB_NODE_CAPSULE: WbNodeType = 6;
pub const WbNodeType_WB_NODE_COLOR: WbNodeType = 7;
pub const WbNodeType_WB_NODE_CONE: WbNodeType = 8;
pub const WbNodeType_WB_NODE_COORDINATE: WbNodeType = 9;
pub const WbNodeType_WB_NODE_CYLINDER: WbNodeType = 10;
pub const WbNodeType_WB_NODE_DIRECTIONAL_LIGHT: WbNodeType = 11;
pub const WbNodeType_WB_NODE_ELEVATION_GRID: WbNodeType = 12;
pub const WbNodeType_WB_NODE_FOG: WbNodeType = 13;
pub const WbNodeType_WB_NODE_GROUP: WbNodeType = 14;
pub const WbNodeType_WB_NODE_IMAGE_TEXTURE: WbNodeType = 15;
pub const WbNodeType_WB_NODE_INDEXED_FACE_SET: WbNodeType = 16;
pub const WbNodeType_WB_NODE_INDEXED_LINE_SET: WbNodeType = 17;
pub const WbNodeType_WB_NODE_MATERIAL: WbNodeType = 18;
pub const WbNodeType_WB_NODE_MESH: WbNodeType = 19;
pub const WbNodeType_WB_NODE_MUSCLE: WbNodeType = 20;
pub const WbNodeType_WB_NODE_NORMAL: WbNodeType = 21;
pub const WbNodeType_WB_NODE_PBR_APPEARANCE: WbNodeType = 22;
pub const WbNodeType_WB_NODE_PLANE: WbNodeType = 23;
pub const WbNodeType_WB_NODE_POINT_LIGHT: WbNodeType = 24;
pub const WbNodeType_WB_NODE_POINT_SET: WbNodeType = 25;
pub const WbNodeType_WB_NODE_POSE: WbNodeType = 26;
pub const WbNodeType_WB_NODE_SHAPE: WbNodeType = 27;
pub const WbNodeType_WB_NODE_SPHERE: WbNodeType = 28;
pub const WbNodeType_WB_NODE_SPOT_LIGHT: WbNodeType = 29;
pub const WbNodeType_WB_NODE_TEXTURE_COORDINATE: WbNodeType = 30;
pub const WbNodeType_WB_NODE_TEXTURE_TRANSFORM: WbNodeType = 31;
pub const WbNodeType_WB_NODE_TRANSFORM: WbNodeType = 32;
pub const WbNodeType_WB_NODE_VIEWPOINT: WbNodeType = 33;
pub const WbNodeType_WB_NODE_ROBOT: WbNodeType = 34;
pub const WbNodeType_WB_NODE_ACCELEROMETER: WbNodeType = 35;
pub const WbNodeType_WB_NODE_ALTIMETER: WbNodeType = 36;
pub const WbNodeType_WB_NODE_BRAKE: WbNodeType = 37;
pub const WbNodeType_WB_NODE_CAMERA: WbNodeType = 38;
pub const WbNodeType_WB_NODE_COMPASS: WbNodeType = 39;
pub const WbNodeType_WB_NODE_CONNECTOR: WbNodeType = 40;
pub const WbNodeType_WB_NODE_DISPLAY: WbNodeType = 41;
pub const WbNodeType_WB_NODE_DISTANCE_SENSOR: WbNodeType = 42;
pub const WbNodeType_WB_NODE_EMITTER: WbNodeType = 43;
pub const WbNodeType_WB_NODE_GPS: WbNodeType = 44;
pub const WbNodeType_WB_NODE_GYRO: WbNodeType = 45;
pub const WbNodeType_WB_NODE_INERTIAL_UNIT: WbNodeType = 46;
pub const WbNodeType_WB_NODE_LED: WbNodeType = 47;
pub const WbNodeType_WB_NODE_LIDAR: WbNodeType = 48;
pub const WbNodeType_WB_NODE_LIGHT_SENSOR: WbNodeType = 49;
pub const WbNodeType_WB_NODE_LINEAR_MOTOR: WbNodeType = 50;
pub const WbNodeType_WB_NODE_PEN: WbNodeType = 51;
pub const WbNodeType_WB_NODE_POSITION_SENSOR: WbNodeType = 52;
pub const WbNodeType_WB_NODE_PROPELLER: WbNodeType = 53;
pub const WbNodeType_WB_NODE_RADAR: WbNodeType = 54;
pub const WbNodeType_WB_NODE_RANGE_FINDER: WbNodeType = 55;
pub const WbNodeType_WB_NODE_RECEIVER: WbNodeType = 56;
pub const WbNodeType_WB_NODE_ROTATIONAL_MOTOR: WbNodeType = 57;
pub const WbNodeType_WB_NODE_SKIN: WbNodeType = 58;
pub const WbNodeType_WB_NODE_SPEAKER: WbNodeType = 59;
pub const WbNodeType_WB_NODE_TOUCH_SENSOR: WbNodeType = 60;
pub const WbNodeType_WB_NODE_VACUUM_GRIPPER: WbNodeType = 61;
pub const WbNodeType_WB_NODE_BALL_JOINT: WbNodeType = 62;
pub const WbNodeType_WB_NODE_BALL_JOINT_PARAMETERS: WbNodeType = 63;
pub const WbNodeType_WB_NODE_CHARGER: WbNodeType = 64;
pub const WbNodeType_WB_NODE_CONTACT_PROPERTIES: WbNodeType = 65;
pub const WbNodeType_WB_NODE_DAMPING: WbNodeType = 66;
pub const WbNodeType_WB_NODE_FLUID: WbNodeType = 67;
pub const WbNodeType_WB_NODE_FOCUS: WbNodeType = 68;
pub const WbNodeType_WB_NODE_HINGE_JOINT: WbNodeType = 69;
pub const WbNodeType_WB_NODE_HINGE_JOINT_PARAMETERS: WbNodeType = 70;
pub const WbNodeType_WB_NODE_HINGE_2_JOINT: WbNodeType = 71;
pub const WbNodeType_WB_NODE_IMMERSION_PROPERTIES: WbNodeType = 72;
pub const WbNodeType_WB_NODE_JOINT_PARAMETERS: WbNodeType = 73;
pub const WbNodeType_WB_NODE_LENS: WbNodeType = 74;
pub const WbNodeType_WB_NODE_LENS_FLARE: WbNodeType = 75;
pub const WbNodeType_WB_NODE_PHYSICS: WbNodeType = 76;
pub const WbNodeType_WB_NODE_RECOGNITION: WbNodeType = 77;
pub const WbNodeType_WB_NODE_SLIDER_JOINT: WbNodeType = 78;
pub const WbNodeType_WB_NODE_SLOT: WbNodeType = 79;
pub const WbNodeType_WB_NODE_SOLID: WbNodeType = 80;
pub const WbNodeType_WB_NODE_SOLID_REFERENCE: WbNodeType = 81;
pub const WbNodeType_WB_NODE_TRACK: WbNodeType = 82;
pub const WbNodeType_WB_NODE_TRACK_WHEEL: WbNodeType = 83;
pub const WbNodeType_WB_NODE_WORLD_INFO: WbNodeType = 84;
pub const WbNodeType_WB_NODE_ZOOM: WbNodeType = 85;
pub const WbNodeType_WB_NODE_MICROPHONE: WbNodeType = 86;
pub const WbNodeType_WB_NODE_RADIO: WbNodeType = 87;
pub type WbNodeType = ::std::os::raw::c_uint;
unsafe extern "C" {
    pub fn wb_node_get_name(t: WbNodeType) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_device_get_name(dt: WbDeviceTag) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_device_get_model(dt: WbDeviceTag) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_device_get_node_type(dt: WbDeviceTag) -> WbNodeType;
}
unsafe extern "C" {
    pub fn wb_device_get_type(dt: WbDeviceTag) -> WbNodeType;
}
unsafe extern "C" {
    pub fn wb_display_get_width(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_display_get_height(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_display_set_color(tag: WbDeviceTag, color: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_display_set_alpha(tag: WbDeviceTag, alpha: f64);
}
unsafe extern "C" {
    pub fn wb_display_set_opacity(tag: WbDeviceTag, opacity: f64);
}
unsafe extern "C" {
    pub fn wb_display_set_font(
        tag: WbDeviceTag,
        font: *const ::std::os::raw::c_char,
        size: ::std::os::raw::c_int,
        anti_aliasing: ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn wb_display_attach_camera(tag: WbDeviceTag, camera_tag: WbDeviceTag);
}
unsafe extern "C" {
    pub fn wb_display_detach_camera(tag: WbDeviceTag);
}
unsafe extern "C" {
    pub fn wb_display_draw_pixel(
        tag: WbDeviceTag,
        x: ::std::os::raw::c_int,
        y: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn wb_display_draw_line(
        tag: WbDeviceTag,
        x1: ::std::os::raw::c_int,
        y1: ::std::os::raw::c_int,
        x2: ::std::os::raw::c_int,
        y2: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn wb_display_draw_rectangle(
        tag: WbDeviceTag,
        x: ::std::os::raw::c_int,
        y: ::std::os::raw::c_int,
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn wb_display_draw_oval(
        tag: WbDeviceTag,
        cx: ::std::os::raw::c_int,
        cy: ::std::os::raw::c_int,
        a: ::std::os::raw::c_int,
        b: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn wb_display_draw_polygon(
        tag: WbDeviceTag,
        x: *const ::std::os::raw::c_int,
        y: *const ::std::os::raw::c_int,
        size: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn wb_display_draw_text(
        tag: WbDeviceTag,
        text: *const ::std::os::raw::c_char,
        x: ::std::os::raw::c_int,
        y: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn wb_display_fill_rectangle(
        tag: WbDeviceTag,
        x: ::std::os::raw::c_int,
        y: ::std::os::raw::c_int,
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn wb_display_fill_oval(
        tag: WbDeviceTag,
        cx: ::std::os::raw::c_int,
        cy: ::std::os::raw::c_int,
        a: ::std::os::raw::c_int,
        b: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn wb_display_fill_polygon(
        tag: WbDeviceTag,
        x: *const ::std::os::raw::c_int,
        y: *const ::std::os::raw::c_int,
        size: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn wb_display_image_new(
        tag: WbDeviceTag,
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
        data: *const ::std::os::raw::c_void,
        format: ::std::os::raw::c_int,
    ) -> WbImageRef;
}
unsafe extern "C" {
    pub fn wb_display_image_copy(
        tag: WbDeviceTag,
        x: ::std::os::raw::c_int,
        y: ::std::os::raw::c_int,
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
    ) -> WbImageRef;
}
unsafe extern "C" {
    pub fn wb_display_image_load(
        tag: WbDeviceTag,
        filename: *const ::std::os::raw::c_char,
    ) -> WbImageRef;
}
unsafe extern "C" {
    pub fn wb_display_image_delete(tag: WbDeviceTag, ir: WbImageRef);
}
unsafe extern "C" {
    pub fn wb_display_image_paste(
        tag: WbDeviceTag,
        ir: WbImageRef,
        x: ::std::os::raw::c_int,
        y: ::std::os::raw::c_int,
        blend: ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn wb_display_image_save(
        tag: WbDeviceTag,
        ir: WbImageRef,
        filename: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn wb_distance_sensor_enable(tag: WbDeviceTag, sampling_period: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_distance_sensor_disable(tag: WbDeviceTag);
}
unsafe extern "C" {
    pub fn wb_distance_sensor_get_sampling_period(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_distance_sensor_get_value(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_distance_sensor_get_max_value(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_distance_sensor_get_min_value(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_distance_sensor_get_aperture(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_distance_sensor_get_lookup_table_size(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_distance_sensor_get_lookup_table(tag: WbDeviceTag) -> *const f64;
}
pub const WbDistanceSensorType_WB_DISTANCE_SENSOR_GENERIC: WbDistanceSensorType = 0;
pub const WbDistanceSensorType_WB_DISTANCE_SENSOR_INFRA_RED: WbDistanceSensorType = 1;
pub const WbDistanceSensorType_WB_DISTANCE_SENSOR_SONAR: WbDistanceSensorType = 2;
pub const WbDistanceSensorType_WB_DISTANCE_SENSOR_LASER: WbDistanceSensorType = 3;
pub type WbDistanceSensorType = ::std::os::raw::c_uint;
unsafe extern "C" {
    pub fn wb_distance_sensor_get_type(tag: WbDeviceTag) -> WbDistanceSensorType;
}
unsafe extern "C" {
    pub fn wb_emitter_send(
        tag: WbDeviceTag,
        data: *const ::std::os::raw::c_void,
        size: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_emitter_get_buffer_size(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_emitter_set_channel(tag: WbDeviceTag, channel: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_emitter_get_channel(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_emitter_get_range(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_emitter_set_range(tag: WbDeviceTag, range: f64);
}
unsafe extern "C" {
    pub fn wb_gps_enable(tag: WbDeviceTag, sampling_period: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_gps_disable(tag: WbDeviceTag);
}
unsafe extern "C" {
    pub fn wb_gps_get_sampling_period(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_gps_get_speed(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_gps_get_speed_vector(tag: WbDeviceTag) -> *const f64;
}
unsafe extern "C" {
    pub fn wb_gps_get_values(tag: WbDeviceTag) -> *const f64;
}
unsafe extern "C" {
    pub fn wb_gps_convert_to_degrees_minutes_seconds(
        decimal_degrees: f64,
    ) -> *const ::std::os::raw::c_char;
}
pub const WbGpsCoordinateSystem_WB_GPS_LOCAL_COORDINATE: WbGpsCoordinateSystem = 0;
pub const WbGpsCoordinateSystem_WB_GPS_WGS84_COORDINATE: WbGpsCoordinateSystem = 1;
pub type WbGpsCoordinateSystem = ::std::os::raw::c_uint;
unsafe extern "C" {
    pub fn wb_gps_get_coordinate_system(tag: WbDeviceTag) -> WbGpsCoordinateSystem;
}
unsafe extern "C" {
    pub fn wb_gyro_enable(tag: WbDeviceTag, sampling_period: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_gyro_disable(tag: WbDeviceTag);
}
unsafe extern "C" {
    pub fn wb_gyro_get_sampling_period(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_gyro_get_lookup_table_size(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_gyro_get_lookup_table(tag: WbDeviceTag) -> *const f64;
}
unsafe extern "C" {
    pub fn wb_gyro_get_values(tag: WbDeviceTag) -> *const f64;
}
unsafe extern "C" {
    pub fn wb_inertial_unit_enable(tag: WbDeviceTag, sampling_period: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_inertial_unit_disable(tag: WbDeviceTag);
}
unsafe extern "C" {
    pub fn wb_inertial_unit_get_sampling_period(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_inertial_unit_get_noise(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_inertial_unit_get_roll_pitch_yaw(tag: WbDeviceTag) -> *const f64;
}
unsafe extern "C" {
    pub fn wb_inertial_unit_get_quaternion(tag: WbDeviceTag) -> *const f64;
}
unsafe extern "C" {
    pub fn wb_joystick_enable(sampling_period: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_joystick_disable();
}
unsafe extern "C" {
    pub fn wb_joystick_get_sampling_period() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_joystick_is_connected() -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_joystick_get_model() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_joystick_get_number_of_axes() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_joystick_get_axis_value(axis: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_joystick_get_number_of_povs() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_joystick_get_pov_value(pov: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_joystick_get_pressed_button() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_joystick_set_constant_force(level: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_joystick_set_constant_force_duration(duration: f64);
}
unsafe extern "C" {
    pub fn wb_joystick_set_auto_centering_gain(gain: f64);
}
unsafe extern "C" {
    pub fn wb_joystick_set_resistance_gain(gain: f64);
}
unsafe extern "C" {
    pub fn wb_joystick_set_force_axis(axis: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_keyboard_enable(sampling_period: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_keyboard_disable();
}
unsafe extern "C" {
    pub fn wb_keyboard_get_sampling_period() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_keyboard_get_key() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_led_set(tag: WbDeviceTag, value: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_led_get(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct WbLidarPoint {
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub layer_id: ::std::os::raw::c_int,
    pub time: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of WbLidarPoint"][::std::mem::size_of::<WbLidarPoint>() - 20usize];
    ["Alignment of WbLidarPoint"][::std::mem::align_of::<WbLidarPoint>() - 4usize];
    ["Offset of field: WbLidarPoint::x"][::std::mem::offset_of!(WbLidarPoint, x) - 0usize];
    ["Offset of field: WbLidarPoint::y"][::std::mem::offset_of!(WbLidarPoint, y) - 4usize];
    ["Offset of field: WbLidarPoint::z"][::std::mem::offset_of!(WbLidarPoint, z) - 8usize];
    ["Offset of field: WbLidarPoint::layer_id"]
        [::std::mem::offset_of!(WbLidarPoint, layer_id) - 12usize];
    ["Offset of field: WbLidarPoint::time"][::std::mem::offset_of!(WbLidarPoint, time) - 16usize];
};
unsafe extern "C" {
    pub fn wb_lidar_enable(tag: WbDeviceTag, sampling_period: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_lidar_enable_point_cloud(tag: WbDeviceTag);
}
unsafe extern "C" {
    pub fn wb_lidar_disable(tag: WbDeviceTag);
}
unsafe extern "C" {
    pub fn wb_lidar_disable_point_cloud(tag: WbDeviceTag);
}
unsafe extern "C" {
    pub fn wb_lidar_get_sampling_period(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_lidar_is_point_cloud_enabled(tag: WbDeviceTag) -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_lidar_get_range_image(tag: WbDeviceTag) -> *const f32;
}
unsafe extern "C" {
    pub fn wb_lidar_get_layer_range_image(
        tag: WbDeviceTag,
        layer: ::std::os::raw::c_int,
    ) -> *const f32;
}
unsafe extern "C" {
    pub fn wb_lidar_get_point_cloud(tag: WbDeviceTag) -> *const WbLidarPoint;
}
unsafe extern "C" {
    pub fn wb_lidar_get_layer_point_cloud(
        tag: WbDeviceTag,
        layer: ::std::os::raw::c_int,
    ) -> *const WbLidarPoint;
}
unsafe extern "C" {
    pub fn wb_lidar_get_number_of_points(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_lidar_get_horizontal_resolution(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_lidar_get_number_of_layers(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_lidar_get_min_frequency(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_lidar_get_max_frequency(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_lidar_get_frequency(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_lidar_set_frequency(tag: WbDeviceTag, frequency: f64);
}
unsafe extern "C" {
    pub fn wb_lidar_get_fov(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_lidar_get_vertical_fov(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_lidar_get_min_range(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_lidar_get_max_range(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_light_sensor_enable(tag: WbDeviceTag, sampling_period: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_light_sensor_disable(tag: WbDeviceTag);
}
unsafe extern "C" {
    pub fn wb_light_sensor_get_sampling_period(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_light_sensor_get_lookup_table_size(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_light_sensor_get_lookup_table(tag: WbDeviceTag) -> *const f64;
}
unsafe extern "C" {
    pub fn wb_light_sensor_get_value(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_microphone_enable(tag: WbDeviceTag, sampling_period: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_microphone_disable(tag: WbDeviceTag);
}
unsafe extern "C" {
    pub fn wb_microphone_get_sampling_period(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_microphone_get_sample_data(tag: WbDeviceTag) -> *const ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn wb_microphone_get_sample_size(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_motor_set_position(tag: WbDeviceTag, position: f64);
}
unsafe extern "C" {
    pub fn wb_motor_set_acceleration(tag: WbDeviceTag, acceleration: f64);
}
unsafe extern "C" {
    pub fn wb_motor_set_velocity(tag: WbDeviceTag, velocity: f64);
}
unsafe extern "C" {
    pub fn wb_motor_set_force(tag: WbDeviceTag, force: f64);
}
unsafe extern "C" {
    pub fn wb_motor_set_torque(tag: WbDeviceTag, torque: f64);
}
unsafe extern "C" {
    pub fn wb_motor_set_available_force(tag: WbDeviceTag, force: f64);
}
unsafe extern "C" {
    pub fn wb_motor_set_available_torque(tag: WbDeviceTag, torque: f64);
}
unsafe extern "C" {
    pub fn wb_motor_set_control_pid(tag: WbDeviceTag, p: f64, i: f64, d: f64);
}
unsafe extern "C" {
    pub fn wb_motor_enable_force_feedback(tag: WbDeviceTag, sampling_period: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_motor_disable_force_feedback(tag: WbDeviceTag);
}
unsafe extern "C" {
    pub fn wb_motor_get_force_feedback_sampling_period(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_motor_get_force_feedback(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_motor_enable_torque_feedback(
        tag: WbDeviceTag,
        sampling_period: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn wb_motor_disable_torque_feedback(tag: WbDeviceTag);
}
unsafe extern "C" {
    pub fn wb_motor_get_torque_feedback_sampling_period(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_motor_get_torque_feedback(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_motor_get_type(tag: WbDeviceTag) -> WbJointType;
}
unsafe extern "C" {
    pub fn wb_motor_get_target_position(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_motor_get_min_position(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_motor_get_max_position(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_motor_get_velocity(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_motor_get_max_velocity(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_motor_get_acceleration(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_motor_get_available_force(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_motor_get_max_force(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_motor_get_available_torque(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_motor_get_max_torque(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_motor_get_multiplier(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_motor_get_brake(tag: WbDeviceTag) -> WbDeviceTag;
}
unsafe extern "C" {
    pub fn wb_motor_get_position_sensor(tag: WbDeviceTag) -> WbDeviceTag;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct WbMouseState {
    pub u: f64,
    pub v: f64,
    pub x: f64,
    pub y: f64,
    pub z: f64,
    pub left: ::std::os::raw::c_char,
    pub middle: ::std::os::raw::c_char,
    pub right: ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of WbMouseState"][::std::mem::size_of::<WbMouseState>() - 48usize];
    ["Alignment of WbMouseState"][::std::mem::align_of::<WbMouseState>() - 8usize];
    ["Offset of field: WbMouseState::u"][::std::mem::offset_of!(WbMouseState, u) - 0usize];
    ["Offset of field: WbMouseState::v"][::std::mem::offset_of!(WbMouseState, v) - 8usize];
    ["Offset of field: WbMouseState::x"][::std::mem::offset_of!(WbMouseState, x) - 16usize];
    ["Offset of field: WbMouseState::y"][::std::mem::offset_of!(WbMouseState, y) - 24usize];
    ["Offset of field: WbMouseState::z"][::std::mem::offset_of!(WbMouseState, z) - 32usize];
    ["Offset of field: WbMouseState::left"][::std::mem::offset_of!(WbMouseState, left) - 40usize];
    ["Offset of field: WbMouseState::middle"]
        [::std::mem::offset_of!(WbMouseState, middle) - 41usize];
    ["Offset of field: WbMouseState::right"][::std::mem::offset_of!(WbMouseState, right) - 42usize];
};
unsafe extern "C" {
    pub fn wb_mouse_enable(sampling_period: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_mouse_disable();
}
unsafe extern "C" {
    pub fn wb_mouse_get_sampling_period() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_mouse_enable_3d_position();
}
unsafe extern "C" {
    pub fn wb_mouse_disable_3d_position();
}
unsafe extern "C" {
    pub fn wb_mouse_is_3d_position_enabled() -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_mouse_get_state() -> WbMouseState;
}
unsafe extern "C" {
    pub fn wb_pen_write(tag: WbDeviceTag, write: ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn wb_pen_set_ink_color(tag: WbDeviceTag, color: ::std::os::raw::c_int, density: f64);
}
unsafe extern "C" {
    pub fn wb_robot_wwi_send(data: *const ::std::os::raw::c_char, size: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_robot_wwi_receive(size: *mut ::std::os::raw::c_int) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_robot_wwi_receive_text() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wbu_default_robot_window_configure();
}
unsafe extern "C" {
    pub fn wbu_default_robot_window_update();
}
unsafe extern "C" {
    pub fn wbu_default_robot_window_set_images_max_size(
        max_width: ::std::os::raw::c_int,
        max_height: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn wbu_generic_robot_window_parse_device_command(
        token: *mut ::std::os::raw::c_char,
        tokens: *mut ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn wbu_generic_robot_window_parse_device_control_command(
        first_token: *const ::std::os::raw::c_char,
        tokens: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wbu_generic_robot_window_handle_messages(
        message: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wbu_generic_robot_window_init();
}
unsafe extern "C" {
    pub fn wbu_generic_robot_window_update();
}
unsafe extern "C" {
    pub fn wbu_generic_robot_window_is_hidden() -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wbu_generic_robot_window_refresh_rate() -> f64;
}
unsafe extern "C" {
    pub fn wbu_generic_robot_window_needs_update() -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_robot_window_custom_function(
        arg1: *mut ::std::os::raw::c_void,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn wb_position_sensor_enable(tag: WbDeviceTag, sampling_period: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_position_sensor_disable(tag: WbDeviceTag);
}
unsafe extern "C" {
    pub fn wb_position_sensor_get_sampling_period(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_position_sensor_get_value(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_position_sensor_get_type(tag: WbDeviceTag) -> WbJointType;
}
unsafe extern "C" {
    pub fn wb_position_sensor_get_motor(tag: WbDeviceTag) -> WbDeviceTag;
}
unsafe extern "C" {
    pub fn wb_position_sensor_get_brake(tag: WbDeviceTag) -> WbDeviceTag;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct WbRadarTarget {
    pub distance: f64,
    pub received_power: f64,
    pub speed: f64,
    pub azimuth: f64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of WbRadarTarget"][::std::mem::size_of::<WbRadarTarget>() - 32usize];
    ["Alignment of WbRadarTarget"][::std::mem::align_of::<WbRadarTarget>() - 8usize];
    ["Offset of field: WbRadarTarget::distance"]
        [::std::mem::offset_of!(WbRadarTarget, distance) - 0usize];
    ["Offset of field: WbRadarTarget::received_power"]
        [::std::mem::offset_of!(WbRadarTarget, received_power) - 8usize];
    ["Offset of field: WbRadarTarget::speed"]
        [::std::mem::offset_of!(WbRadarTarget, speed) - 16usize];
    ["Offset of field: WbRadarTarget::azimuth"]
        [::std::mem::offset_of!(WbRadarTarget, azimuth) - 24usize];
};
unsafe extern "C" {
    pub fn wb_radar_enable(tag: WbDeviceTag, sampling_period: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_radar_disable(tag: WbDeviceTag);
}
unsafe extern "C" {
    pub fn wb_radar_get_sampling_period(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_radar_get_number_of_targets(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_radar_get_targets(tag: WbDeviceTag) -> *const WbRadarTarget;
}
unsafe extern "C" {
    pub fn wb_radar_get_min_range(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_radar_get_max_range(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_radar_get_horizontal_fov(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_radar_get_vertical_fov(tag: WbDeviceTag) -> f64;
}
pub type WbRadioMessage = *mut ::std::os::raw::c_void;
pub type WbRadioEvent = *mut ::std::os::raw::c_void;
unsafe extern "C" {
    pub fn wb_radio_message_new(
        length: ::std::os::raw::c_int,
        body: *const ::std::os::raw::c_char,
        destination: *const ::std::os::raw::c_char,
    ) -> WbRadioMessage;
}
unsafe extern "C" {
    pub fn wb_radio_message_delete(arg1: WbRadioMessage);
}
unsafe extern "C" {
    pub fn wb_radio_message_get_destination(arg1: WbRadioMessage) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_radio_message_get_length(arg1: WbRadioMessage) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_radio_message_get_body(arg1: WbRadioMessage) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_radio_enable(tag: WbDeviceTag, sampling_period: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_radio_disable(tag: WbDeviceTag);
}
unsafe extern "C" {
    pub fn wb_radio_set_address(tag: WbDeviceTag, address: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn wb_radio_get_address(tag: WbDeviceTag) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_radio_set_frequency(tag: WbDeviceTag, hz: f64);
}
unsafe extern "C" {
    pub fn wb_radio_get_frequency(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_radio_set_channel(tag: WbDeviceTag, channel: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_radio_get_channel(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_radio_set_bitrate(tag: WbDeviceTag, bits_per_second: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_radio_get_bitrate(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_radio_set_rx_sensitivity(tag: WbDeviceTag, dBm: f64);
}
unsafe extern "C" {
    pub fn wb_radio_get_rx_sensitivity(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_radio_set_tx_power(tag: WbDeviceTag, dBm: f64);
}
unsafe extern "C" {
    pub fn wb_radio_get_tx_power(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_radio_set_callback(
        tag: WbDeviceTag,
        arg1: ::std::option::Option<unsafe extern "C" fn(arg1: WbRadioEvent)>,
    );
}
unsafe extern "C" {
    pub fn wb_radio_event_get_radio(arg1: WbRadioEvent) -> WbDeviceTag;
}
unsafe extern "C" {
    pub fn wb_radio_event_get_data(arg1: WbRadioEvent) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_radio_event_get_data_size(arg1: WbRadioEvent) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_radio_event_get_emitter(arg1: WbRadioEvent) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_radio_event_get_rssi(arg1: WbRadioEvent) -> f64;
}
unsafe extern "C" {
    pub fn wb_radio_send(tag: WbDeviceTag, arg1: WbRadioMessage, delay: f64);
}
unsafe extern "C" {
    pub fn wb_range_finder_enable(tag: WbDeviceTag, sampling_period: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_range_finder_disable(tag: WbDeviceTag);
}
unsafe extern "C" {
    pub fn wb_range_finder_get_sampling_period(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_range_finder_get_range_image(tag: WbDeviceTag) -> *const f32;
}
unsafe extern "C" {
    pub fn wb_range_finder_get_width(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_range_finder_get_height(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_range_finder_get_fov(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_range_finder_get_min_range(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_range_finder_get_max_range(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_range_finder_save_image(
        tag: WbDeviceTag,
        filename: *const ::std::os::raw::c_char,
        quality: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_receiver_enable(tag: WbDeviceTag, sampling_period: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_receiver_disable(tag: WbDeviceTag);
}
unsafe extern "C" {
    pub fn wb_receiver_get_sampling_period(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_receiver_set_channel(tag: WbDeviceTag, channel: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_receiver_get_channel(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_receiver_get_queue_length(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_receiver_next_packet(tag: WbDeviceTag);
}
unsafe extern "C" {
    pub fn wb_receiver_get_data_size(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_receiver_get_data(tag: WbDeviceTag) -> *const ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn wb_receiver_get_signal_strength(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_receiver_get_emitter_direction(tag: WbDeviceTag) -> *const f64;
}
unsafe extern "C" {
    pub fn wb_remote_control_custom_function(
        arg1: *mut ::std::os::raw::c_void,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn wbr_robot_battery_sensor_set_value(value: f64);
}
unsafe extern "C" {
    pub fn wbr_accelerometer_set_values(tag: WbDeviceTag, values: *const f64);
}
unsafe extern "C" {
    pub fn wbr_camera_recognition_set_object(
        tag: WbDeviceTag,
        objects: *const WbCameraRecognitionObject,
        object_number: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn wbr_compass_set_values(tag: WbDeviceTag, values: *const f64);
}
unsafe extern "C" {
    pub fn wbr_distance_sensor_set_value(tag: WbDeviceTag, value: f64);
}
unsafe extern "C" {
    pub fn wbr_gps_set_values(tag: WbDeviceTag, values: *const f64);
}
unsafe extern "C" {
    pub fn wbr_gps_set_speed(tag: WbDeviceTag, speed: f64);
}
unsafe extern "C" {
    pub fn wbr_gps_set_velocity_vector(tag: WbDeviceTag, values: *const f64);
}
unsafe extern "C" {
    pub fn wbr_gyro_set_values(tag: WbDeviceTag, values: *const f64);
}
unsafe extern "C" {
    pub fn wbr_inertial_unit_set_value(tag: WbDeviceTag, value: f64);
}
unsafe extern "C" {
    pub fn wbr_light_sensor_set_value(tag: WbDeviceTag, value: f64);
}
unsafe extern "C" {
    pub fn wbr_microphone_set_buffer(
        tag: WbDeviceTag,
        buffer: *const ::std::os::raw::c_uchar,
        size: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn wbr_motor_set_position_feedback(tag: WbDeviceTag, value: f64);
}
unsafe extern "C" {
    pub fn wbr_motor_set_force_feedback(tag: WbDeviceTag, value: f64);
}
unsafe extern "C" {
    pub fn wbr_motor_set_torque_feedback(tag: WbDeviceTag, value: f64);
}
unsafe extern "C" {
    pub fn wbr_position_sensor_set_value(tag: WbDeviceTag, value: f64);
}
unsafe extern "C" {
    pub fn wbr_radar_set_targets(
        tag: WbDeviceTag,
        targets: *const WbRadarTarget,
        target_number: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn wbr_touch_sensor_set_value(tag: WbDeviceTag, value: f64);
}
unsafe extern "C" {
    pub fn wbr_touch_sensor_set_values(tag: WbDeviceTag, values: *const f64);
}
unsafe extern "C" {
    pub fn wbr_display_save_image(
        tag: WbDeviceTag,
        id: ::std::os::raw::c_int,
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
        image: *mut ::std::os::raw::c_uchar,
    );
}
unsafe extern "C" {
    pub fn wbr_camera_set_image(tag: WbDeviceTag, image: *const ::std::os::raw::c_uchar);
}
unsafe extern "C" {
    pub fn wbr_camera_get_image_buffer(tag: WbDeviceTag) -> *mut ::std::os::raw::c_uchar;
}
pub type WbMutexRef = *mut ::std::os::raw::c_void;
pub const WbRobotMode_WB_MODE_SIMULATION: WbRobotMode = 0;
pub const WbRobotMode_WB_MODE_CROSS_COMPILATION: WbRobotMode = 1;
pub const WbRobotMode_WB_MODE_REMOTE_CONTROL: WbRobotMode = 2;
pub type WbRobotMode = ::std::os::raw::c_uint;
pub const WbUserInputEvent_WB_EVENT_QUIT: WbUserInputEvent = -1;
pub const WbUserInputEvent_WB_EVENT_NO_EVENT: WbUserInputEvent = 0;
pub const WbUserInputEvent_WB_EVENT_MOUSE_CLICK: WbUserInputEvent = 1;
pub const WbUserInputEvent_WB_EVENT_MOUSE_MOVE: WbUserInputEvent = 2;
pub const WbUserInputEvent_WB_EVENT_KEYBOARD: WbUserInputEvent = 4;
pub const WbUserInputEvent_WB_EVENT_JOYSTICK_BUTTON: WbUserInputEvent = 8;
pub const WbUserInputEvent_WB_EVENT_JOYSTICK_AXIS: WbUserInputEvent = 16;
pub const WbUserInputEvent_WB_EVENT_JOYSTICK_POV: WbUserInputEvent = 32;
pub type WbUserInputEvent = ::std::os::raw::c_int;
unsafe extern "C" {
    pub fn wb_robot_init() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_robot_step_begin(duration: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_robot_step_end() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_robot_step(duration: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_robot_wait_for_user_input_event(
        event_type: WbUserInputEvent,
        timeout: ::std::os::raw::c_int,
    ) -> WbUserInputEvent;
}
unsafe extern "C" {
    pub fn wb_robot_cleanup();
}
unsafe extern "C" {
    pub fn wb_robot_get_time() -> f64;
}
unsafe extern "C" {
    pub fn wb_robot_get_urdf(
        prefix: *const ::std::os::raw::c_char,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_robot_get_name() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_robot_get_model() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_robot_get_custom_data() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_robot_set_custom_data(data: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn wb_robot_get_mode() -> WbRobotMode;
}
unsafe extern "C" {
    pub fn wb_robot_set_mode(mode: WbRobotMode, arg: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn wb_robot_get_synchronization() -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_robot_get_supervisor() -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_robot_get_project_path() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_robot_get_world_path() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_robot_get_basic_time_step() -> f64;
}
unsafe extern "C" {
    pub fn wb_robot_get_device(name: *const ::std::os::raw::c_char) -> WbDeviceTag;
}
unsafe extern "C" {
    pub fn wb_robot_get_number_of_devices() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_robot_get_device_by_index(index: ::std::os::raw::c_int) -> WbDeviceTag;
}
unsafe extern "C" {
    pub fn wb_robot_battery_sensor_enable(sampling_period: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_robot_battery_sensor_disable();
}
unsafe extern "C" {
    pub fn wb_robot_battery_sensor_get_sampling_period() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_robot_battery_sensor_get_value() -> f64;
}
unsafe extern "C" {
    pub fn wb_robot_task_new(
        task: ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
        param: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn wb_robot_mutex_new() -> WbMutexRef;
}
unsafe extern "C" {
    pub fn wb_robot_mutex_lock(arg1: WbMutexRef);
}
unsafe extern "C" {
    pub fn wb_robot_mutex_unlock(arg1: WbMutexRef);
}
unsafe extern "C" {
    pub fn wb_robot_mutex_delete(arg1: WbMutexRef);
}
unsafe extern "C" {
    pub fn wb_robot_pin_to_static_environment(pin: ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn wb_robot_get_controller_name() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_robot_get_data() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_robot_set_data(data: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn wb_skin_set_bone_orientation(
        tag: WbDeviceTag,
        index: ::std::os::raw::c_int,
        orientation: *const f64,
        absolute: ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn wb_skin_set_bone_position(
        tag: WbDeviceTag,
        index: ::std::os::raw::c_int,
        position: *const f64,
        absolute: ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn wb_skin_get_bone_count(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_skin_get_bone_name(
        tag: WbDeviceTag,
        index: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_skin_get_bone_orientation(
        tag: WbDeviceTag,
        index: ::std::os::raw::c_int,
        absolute: ::std::os::raw::c_char,
    ) -> *const f64;
}
unsafe extern "C" {
    pub fn wb_skin_get_bone_position(
        tag: WbDeviceTag,
        index: ::std::os::raw::c_int,
        absolute: ::std::os::raw::c_char,
    ) -> *const f64;
}
unsafe extern "C" {
    pub fn wb_speaker_play_sound(
        left: WbDeviceTag,
        right: WbDeviceTag,
        sound: *const ::std::os::raw::c_char,
        volume: f64,
        pitch: f64,
        balance: f64,
        loop_: ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn wb_speaker_stop(tag: WbDeviceTag, sound: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn wb_speaker_is_sound_playing(
        tag: WbDeviceTag,
        sound: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_speaker_set_engine(
        tag: WbDeviceTag,
        engine: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_speaker_set_language(
        tag: WbDeviceTag,
        language: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_speaker_get_engine(tag: WbDeviceTag) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_speaker_get_language(tag: WbDeviceTag) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_speaker_speak(tag: WbDeviceTag, text: *const ::std::os::raw::c_char, volume: f64);
}
unsafe extern "C" {
    pub fn wb_speaker_is_speaking(tag: WbDeviceTag) -> ::std::os::raw::c_char;
}
pub const WbFieldType_WB_NO_FIELD: WbFieldType = 0;
pub const WbFieldType_WB_SF_BOOL: WbFieldType = 1;
pub const WbFieldType_WB_SF_INT32: WbFieldType = 2;
pub const WbFieldType_WB_SF_FLOAT: WbFieldType = 3;
pub const WbFieldType_WB_SF_VEC2F: WbFieldType = 4;
pub const WbFieldType_WB_SF_VEC3F: WbFieldType = 5;
pub const WbFieldType_WB_SF_ROTATION: WbFieldType = 6;
pub const WbFieldType_WB_SF_COLOR: WbFieldType = 7;
pub const WbFieldType_WB_SF_STRING: WbFieldType = 8;
pub const WbFieldType_WB_SF_NODE: WbFieldType = 9;
pub const WbFieldType_WB_MF: WbFieldType = 16;
pub const WbFieldType_WB_MF_BOOL: WbFieldType = 17;
pub const WbFieldType_WB_MF_INT32: WbFieldType = 18;
pub const WbFieldType_WB_MF_FLOAT: WbFieldType = 19;
pub const WbFieldType_WB_MF_VEC2F: WbFieldType = 20;
pub const WbFieldType_WB_MF_VEC3F: WbFieldType = 21;
pub const WbFieldType_WB_MF_ROTATION: WbFieldType = 22;
pub const WbFieldType_WB_MF_COLOR: WbFieldType = 23;
pub const WbFieldType_WB_MF_STRING: WbFieldType = 24;
pub const WbFieldType_WB_MF_NODE: WbFieldType = 25;
pub type WbFieldType = ::std::os::raw::c_uint;
pub const WbSimulationMode_WB_SUPERVISOR_SIMULATION_MODE_PAUSE: WbSimulationMode = 0;
pub const WbSimulationMode_WB_SUPERVISOR_SIMULATION_MODE_REAL_TIME: WbSimulationMode = 1;
pub const WbSimulationMode_WB_SUPERVISOR_SIMULATION_MODE_FAST: WbSimulationMode = 2;
pub type WbSimulationMode = ::std::os::raw::c_uint;
unsafe extern "C" {
    pub fn wb_supervisor_world_load(filename: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn wb_supervisor_world_save(
        filename: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_supervisor_world_reload();
}
unsafe extern "C" {
    pub fn wb_supervisor_simulation_quit(status: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_supervisor_simulation_reset();
}
unsafe extern "C" {
    pub fn wb_supervisor_simulation_reset_physics();
}
unsafe extern "C" {
    pub fn wb_supervisor_simulation_get_mode() -> WbSimulationMode;
}
unsafe extern "C" {
    pub fn wb_supervisor_simulation_set_mode(mode: WbSimulationMode);
}
unsafe extern "C" {
    pub fn wb_supervisor_set_label(
        id: ::std::os::raw::c_int,
        text: *const ::std::os::raw::c_char,
        x: f64,
        y: f64,
        size: f64,
        color: ::std::os::raw::c_int,
        transparency: f64,
        font: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn wb_supervisor_export_image(
        filename: *const ::std::os::raw::c_char,
        quality: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn wb_supervisor_movie_start_recording(
        filename: *const ::std::os::raw::c_char,
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
        codec: ::std::os::raw::c_int,
        quality: ::std::os::raw::c_int,
        acceleration: ::std::os::raw::c_int,
        caption: ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn wb_supervisor_movie_stop_recording();
}
unsafe extern "C" {
    pub fn wb_supervisor_movie_is_ready() -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_supervisor_movie_failed() -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_supervisor_animation_start_recording(
        filename: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_supervisor_animation_stop_recording() -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_supervisor_node_get_root() -> WbNodeRef;
}
unsafe extern "C" {
    pub fn wb_supervisor_node_get_self() -> WbNodeRef;
}
unsafe extern "C" {
    pub fn wb_supervisor_node_get_id(node: WbNodeRef) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_supervisor_node_get_from_id(id: ::std::os::raw::c_int) -> WbNodeRef;
}
unsafe extern "C" {
    pub fn wb_supervisor_node_get_from_device(tag: WbDeviceTag) -> WbNodeRef;
}
unsafe extern "C" {
    pub fn wb_supervisor_node_get_from_def(def: *const ::std::os::raw::c_char) -> WbNodeRef;
}
unsafe extern "C" {
    pub fn wb_supervisor_node_get_from_proto_def(
        node: WbNodeRef,
        def: *const ::std::os::raw::c_char,
    ) -> WbNodeRef;
}
unsafe extern "C" {
    pub fn wb_supervisor_node_get_parent_node(node: WbNodeRef) -> WbNodeRef;
}
unsafe extern "C" {
    pub fn wb_supervisor_node_get_selected() -> WbNodeRef;
}
unsafe extern "C" {
    pub fn wb_supervisor_node_get_type(node: WbNodeRef) -> WbNodeType;
}
unsafe extern "C" {
    pub fn wb_supervisor_node_get_field(
        node: WbNodeRef,
        field_name: *const ::std::os::raw::c_char,
    ) -> WbFieldRef;
}
unsafe extern "C" {
    pub fn wb_supervisor_node_get_field_by_index(
        node: WbNodeRef,
        index: ::std::os::raw::c_int,
    ) -> WbFieldRef;
}
unsafe extern "C" {
    pub fn wb_supervisor_node_get_number_of_fields(node: WbNodeRef) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_supervisor_node_get_base_node_field(
        node: WbNodeRef,
        field_name: *const ::std::os::raw::c_char,
    ) -> WbFieldRef;
}
unsafe extern "C" {
    pub fn wb_supervisor_node_get_base_node_field_by_index(
        node: WbNodeRef,
        index: ::std::os::raw::c_int,
    ) -> WbFieldRef;
}
unsafe extern "C" {
    pub fn wb_supervisor_node_get_number_of_base_node_fields(
        node: WbNodeRef,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_supervisor_node_remove(node: WbNodeRef);
}
unsafe extern "C" {
    pub fn wb_supervisor_node_save_state(
        node: WbNodeRef,
        state_name: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn wb_supervisor_node_load_state(
        node: WbNodeRef,
        state_name: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn wb_supervisor_node_set_joint_position(
        node: WbNodeRef,
        position: f64,
        index: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn wb_supervisor_node_get_proto(node: WbNodeRef) -> WbProtoRef;
}
unsafe extern "C" {
    pub fn wb_supervisor_node_get_def(node: WbNodeRef) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_supervisor_node_get_type_name(node: WbNodeRef) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_supervisor_node_get_base_type_name(node: WbNodeRef) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_supervisor_node_is_proto(node: WbNodeRef) -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_supervisor_node_get_center_of_mass(node: WbNodeRef) -> *const f64;
}
unsafe extern "C" {
    pub fn wb_supervisor_node_get_contact_point(
        node: WbNodeRef,
        index: ::std::os::raw::c_int,
    ) -> *const f64;
}
unsafe extern "C" {
    pub fn wb_supervisor_node_get_contact_point_node(
        node: WbNodeRef,
        index: ::std::os::raw::c_int,
    ) -> WbNodeRef;
}
unsafe extern "C" {
    pub fn wb_supervisor_node_get_number_of_contact_points(
        node: WbNodeRef,
        include_descendants: ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_supervisor_node_get_contact_points(
        node: WbNodeRef,
        include_descendants: ::std::os::raw::c_char,
        size: *mut ::std::os::raw::c_int,
    ) -> *mut WbContactPoint;
}
unsafe extern "C" {
    pub fn wb_supervisor_node_get_orientation(node: WbNodeRef) -> *const f64;
}
unsafe extern "C" {
    pub fn wb_supervisor_node_get_position(node: WbNodeRef) -> *const f64;
}
unsafe extern "C" {
    pub fn wb_supervisor_node_get_pose(node: WbNodeRef, from_node: WbNodeRef) -> *const f64;
}
unsafe extern "C" {
    pub fn wb_supervisor_node_get_static_balance(node: WbNodeRef) -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_supervisor_node_get_velocity(node: WbNodeRef) -> *const f64;
}
unsafe extern "C" {
    pub fn wb_supervisor_node_set_velocity(node: WbNodeRef, velocity: *const f64);
}
unsafe extern "C" {
    pub fn wb_supervisor_node_reset_physics(node: WbNodeRef);
}
unsafe extern "C" {
    pub fn wb_supervisor_node_restart_controller(node: WbNodeRef);
}
unsafe extern "C" {
    pub fn wb_supervisor_node_export_string(node: WbNodeRef) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_supervisor_node_move_viewpoint(node: WbNodeRef);
}
unsafe extern "C" {
    pub fn wb_supervisor_node_set_visibility(
        node: WbNodeRef,
        from: WbNodeRef,
        visible: ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn wb_supervisor_node_add_force(
        node: WbNodeRef,
        force: *const f64,
        relative: ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn wb_supervisor_node_add_force_with_offset(
        node: WbNodeRef,
        force: *const f64,
        offset: *const f64,
        relative: ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn wb_supervisor_node_add_torque(
        node: WbNodeRef,
        torque: *const f64,
        relative: ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn wb_supervisor_field_get_name(field: WbFieldRef) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_supervisor_field_get_type(field: WbFieldRef) -> WbFieldType;
}
unsafe extern "C" {
    pub fn wb_supervisor_field_get_type_name(field: WbFieldRef) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_supervisor_field_get_count(field: WbFieldRef) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_supervisor_field_get_actual_field(field: WbFieldRef) -> WbFieldRef;
}
unsafe extern "C" {
    pub fn wb_supervisor_field_enable_sf_tracking(
        field: WbFieldRef,
        sampling_period: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn wb_supervisor_field_disable_sf_tracking(field: WbFieldRef);
}
unsafe extern "C" {
    pub fn wb_supervisor_node_enable_pose_tracking(
        node: WbNodeRef,
        sampling_period: ::std::os::raw::c_int,
        from_node: WbNodeRef,
    );
}
unsafe extern "C" {
    pub fn wb_supervisor_node_disable_pose_tracking(node: WbNodeRef, from_node: WbNodeRef);
}
unsafe extern "C" {
    pub fn wb_supervisor_node_enable_contact_points_tracking(
        node: WbNodeRef,
        sampling_period: ::std::os::raw::c_int,
        include_descendants: ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn wb_supervisor_node_disable_contact_points_tracking(node: WbNodeRef);
}
unsafe extern "C" {
    pub fn wb_supervisor_field_get_sf_bool(field: WbFieldRef) -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_supervisor_field_get_sf_int32(field: WbFieldRef) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_supervisor_field_get_sf_float(field: WbFieldRef) -> f64;
}
unsafe extern "C" {
    pub fn wb_supervisor_field_get_sf_vec2f(field: WbFieldRef) -> *const f64;
}
unsafe extern "C" {
    pub fn wb_supervisor_field_get_sf_vec3f(field: WbFieldRef) -> *const f64;
}
unsafe extern "C" {
    pub fn wb_supervisor_field_get_sf_rotation(field: WbFieldRef) -> *const f64;
}
unsafe extern "C" {
    pub fn wb_supervisor_field_get_sf_color(field: WbFieldRef) -> *const f64;
}
unsafe extern "C" {
    pub fn wb_supervisor_field_get_sf_string(field: WbFieldRef) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_supervisor_field_get_sf_node(field: WbFieldRef) -> WbNodeRef;
}
unsafe extern "C" {
    pub fn wb_supervisor_field_get_mf_bool(
        field: WbFieldRef,
        index: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_supervisor_field_get_mf_int32(
        field: WbFieldRef,
        index: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_supervisor_field_get_mf_float(field: WbFieldRef, index: ::std::os::raw::c_int)
        -> f64;
}
unsafe extern "C" {
    pub fn wb_supervisor_field_get_mf_vec2f(
        field: WbFieldRef,
        index: ::std::os::raw::c_int,
    ) -> *const f64;
}
unsafe extern "C" {
    pub fn wb_supervisor_field_get_mf_vec3f(
        field: WbFieldRef,
        index: ::std::os::raw::c_int,
    ) -> *const f64;
}
unsafe extern "C" {
    pub fn wb_supervisor_field_get_mf_color(
        field: WbFieldRef,
        index: ::std::os::raw::c_int,
    ) -> *const f64;
}
unsafe extern "C" {
    pub fn wb_supervisor_field_get_mf_rotation(
        field: WbFieldRef,
        index: ::std::os::raw::c_int,
    ) -> *const f64;
}
unsafe extern "C" {
    pub fn wb_supervisor_field_get_mf_string(
        field: WbFieldRef,
        index: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_supervisor_field_get_mf_node(
        field: WbFieldRef,
        index: ::std::os::raw::c_int,
    ) -> WbNodeRef;
}
unsafe extern "C" {
    pub fn wb_supervisor_field_set_sf_bool(field: WbFieldRef, value: ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn wb_supervisor_field_set_sf_int32(field: WbFieldRef, value: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_supervisor_field_set_sf_float(field: WbFieldRef, value: f64);
}
unsafe extern "C" {
    pub fn wb_supervisor_field_set_sf_vec2f(field: WbFieldRef, values: *const f64);
}
unsafe extern "C" {
    pub fn wb_supervisor_field_set_sf_vec3f(field: WbFieldRef, values: *const f64);
}
unsafe extern "C" {
    pub fn wb_supervisor_field_set_sf_rotation(field: WbFieldRef, values: *const f64);
}
unsafe extern "C" {
    pub fn wb_supervisor_field_set_sf_color(field: WbFieldRef, values: *const f64);
}
unsafe extern "C" {
    pub fn wb_supervisor_field_set_sf_string(
        field: WbFieldRef,
        value: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn wb_supervisor_field_set_mf_bool(
        field: WbFieldRef,
        index: ::std::os::raw::c_int,
        value: ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn wb_supervisor_field_set_mf_int32(
        field: WbFieldRef,
        index: ::std::os::raw::c_int,
        value: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn wb_supervisor_field_set_mf_float(
        field: WbFieldRef,
        index: ::std::os::raw::c_int,
        value: f64,
    );
}
unsafe extern "C" {
    pub fn wb_supervisor_field_set_mf_vec2f(
        field: WbFieldRef,
        index: ::std::os::raw::c_int,
        values: *const f64,
    );
}
unsafe extern "C" {
    pub fn wb_supervisor_field_set_mf_vec3f(
        field: WbFieldRef,
        index: ::std::os::raw::c_int,
        values: *const f64,
    );
}
unsafe extern "C" {
    pub fn wb_supervisor_field_set_mf_rotation(
        field: WbFieldRef,
        index: ::std::os::raw::c_int,
        values: *const f64,
    );
}
unsafe extern "C" {
    pub fn wb_supervisor_field_set_mf_color(
        field: WbFieldRef,
        index: ::std::os::raw::c_int,
        values: *const f64,
    );
}
unsafe extern "C" {
    pub fn wb_supervisor_field_set_mf_string(
        field: WbFieldRef,
        index: ::std::os::raw::c_int,
        value: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn wb_supervisor_field_insert_mf_bool(
        field: WbFieldRef,
        index: ::std::os::raw::c_int,
        value: ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn wb_supervisor_field_insert_mf_int32(
        field: WbFieldRef,
        index: ::std::os::raw::c_int,
        value: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn wb_supervisor_field_insert_mf_float(
        field: WbFieldRef,
        index: ::std::os::raw::c_int,
        value: f64,
    );
}
unsafe extern "C" {
    pub fn wb_supervisor_field_insert_mf_vec2f(
        field: WbFieldRef,
        index: ::std::os::raw::c_int,
        values: *const f64,
    );
}
unsafe extern "C" {
    pub fn wb_supervisor_field_insert_mf_vec3f(
        field: WbFieldRef,
        index: ::std::os::raw::c_int,
        values: *const f64,
    );
}
unsafe extern "C" {
    pub fn wb_supervisor_field_insert_mf_rotation(
        field: WbFieldRef,
        index: ::std::os::raw::c_int,
        values: *const f64,
    );
}
unsafe extern "C" {
    pub fn wb_supervisor_field_insert_mf_color(
        field: WbFieldRef,
        index: ::std::os::raw::c_int,
        values: *const f64,
    );
}
unsafe extern "C" {
    pub fn wb_supervisor_field_insert_mf_string(
        field: WbFieldRef,
        index: ::std::os::raw::c_int,
        value: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn wb_supervisor_field_remove_mf(field: WbFieldRef, index: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_supervisor_field_import_mf_node_from_string(
        field: WbFieldRef,
        position: ::std::os::raw::c_int,
        node_string: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn wb_supervisor_field_remove_sf(field: WbFieldRef);
}
unsafe extern "C" {
    pub fn wb_supervisor_field_import_sf_node_from_string(
        field: WbFieldRef,
        node_string: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn wb_supervisor_proto_get_type_name(proto: WbProtoRef) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_supervisor_proto_is_derived(proto: WbProtoRef) -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_supervisor_proto_get_parent(proto: WbProtoRef) -> WbProtoRef;
}
unsafe extern "C" {
    pub fn wb_supervisor_proto_get_field(
        proto: WbProtoRef,
        field_name: *const ::std::os::raw::c_char,
    ) -> WbFieldRef;
}
unsafe extern "C" {
    pub fn wb_supervisor_proto_get_field_by_index(
        proto: WbProtoRef,
        index: ::std::os::raw::c_int,
    ) -> WbFieldRef;
}
unsafe extern "C" {
    pub fn wb_supervisor_proto_get_number_of_fields(proto: WbProtoRef) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_supervisor_virtual_reality_headset_is_used() -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_supervisor_virtual_reality_headset_get_position() -> *const f64;
}
unsafe extern "C" {
    pub fn wb_supervisor_virtual_reality_headset_get_orientation() -> *const f64;
}
unsafe extern "C" {
    pub fn wb_supervisor_node_enable_contact_point_tracking(
        node: WbNodeRef,
        sampling_period: ::std::os::raw::c_int,
        include_descendants: ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn wb_supervisor_node_disable_contact_point_tracking(
        node: WbNodeRef,
        include_descendants: ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn wb_supervisor_simulation_revert();
}
unsafe extern "C" {
    pub fn wb_supervisor_load_world(filename: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn wb_supervisor_save_world(
        filename: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_supervisor_field_remove_mf_node(field: WbFieldRef, position: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_supervisor_simulation_physics_reset();
}
unsafe extern "C" {
    pub fn wb_supervisor_movie_get_status() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_supervisor_start_movie(
        file: *const ::std::os::raw::c_char,
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
        codec: ::std::os::raw::c_int,
        quality: ::std::os::raw::c_int,
        acceleration: ::std::os::raw::c_int,
        caption: ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn wb_supervisor_stop_movie();
}
unsafe extern "C" {
    pub fn wb_supervisor_get_movie_status() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_touch_sensor_enable(tag: WbDeviceTag, sampling_period: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wb_touch_sensor_disable(tag: WbDeviceTag);
}
unsafe extern "C" {
    pub fn wb_touch_sensor_get_sampling_period(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_touch_sensor_get_lookup_table_size(tag: WbDeviceTag) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_touch_sensor_get_lookup_table(tag: WbDeviceTag) -> *const f64;
}
unsafe extern "C" {
    pub fn wb_touch_sensor_get_value(tag: WbDeviceTag) -> f64;
}
unsafe extern "C" {
    pub fn wb_touch_sensor_get_values(tag: WbDeviceTag) -> *const f64;
}
pub const WbTouchSensorType_WB_TOUCH_SENSOR_BUMPER: WbTouchSensorType = 0;
pub const WbTouchSensorType_WB_TOUCH_SENSOR_FORCE: WbTouchSensorType = 1;
pub const WbTouchSensorType_WB_TOUCH_SENSOR_FORCE3D: WbTouchSensorType = 2;
pub type WbTouchSensorType = ::std::os::raw::c_uint;
unsafe extern "C" {
    pub fn wb_touch_sensor_get_type(tag: WbDeviceTag) -> WbTouchSensorType;
}
unsafe extern "C" {
    pub fn wbu_motion_new(filename: *const ::std::os::raw::c_char) -> WbMotionRef;
}
unsafe extern "C" {
    pub fn wbu_motion_delete(motion: WbMotionRef);
}
unsafe extern "C" {
    pub fn wbu_motion_play(motion: WbMotionRef);
}
unsafe extern "C" {
    pub fn wbu_motion_stop(motion: WbMotionRef);
}
unsafe extern "C" {
    pub fn wbu_motion_set_loop(motion: WbMotionRef, loop_: ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn wbu_motion_set_reverse(motion: WbMotionRef, reverse: ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn wbu_motion_is_over(motion: WbMotionRef) -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wbu_motion_get_duration(motion: WbMotionRef) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wbu_motion_get_time(motion: WbMotionRef) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wbu_motion_set_time(motion: WbMotionRef, time: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wbu_string_strsep(
        stringp: *mut *mut ::std::os::raw::c_char,
        delim: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wbu_string_replace(
        value: *mut ::std::os::raw::c_char,
        before: *const ::std::os::raw::c_char,
        after: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wbu_system_getenv(
        variable: *const ::std::os::raw::c_char,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wbu_system_short_path(
        path: *const ::std::os::raw::c_char,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wbu_system_tmpdir() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wbu_system_webots_instance_path(
        refresh: ::std::os::raw::c_char,
    ) -> *const ::std::os::raw::c_char;
}
pub const WbuCarType_WBU_CAR_TRACTION: WbuCarType = 0;
pub const WbuCarType_WBU_CAR_PROPULSION: WbuCarType = 1;
pub const WbuCarType_WBU_CAR_FOUR_BY_FOUR: WbuCarType = 2;
pub type WbuCarType = ::std::os::raw::c_uint;
pub const WbuCarEngineType_WBU_CAR_COMBUSTION_ENGINE: WbuCarEngineType = 0;
pub const WbuCarEngineType_WBU_CAR_ELECTRIC_ENGINE: WbuCarEngineType = 1;
pub const WbuCarEngineType_WBU_CAR_PARALLEL_HYBRID_ENGINE: WbuCarEngineType = 2;
pub const WbuCarEngineType_WBU_CAR_POWER_SPLIT_HYBRID_ENGINE: WbuCarEngineType = 3;
pub type WbuCarEngineType = ::std::os::raw::c_uint;
pub const WbuCarWheelIndex_WBU_CAR_WHEEL_FRONT_RIGHT: WbuCarWheelIndex = 0;
pub const WbuCarWheelIndex_WBU_CAR_WHEEL_FRONT_LEFT: WbuCarWheelIndex = 1;
pub const WbuCarWheelIndex_WBU_CAR_WHEEL_REAR_RIGHT: WbuCarWheelIndex = 2;
pub const WbuCarWheelIndex_WBU_CAR_WHEEL_REAR_LEFT: WbuCarWheelIndex = 3;
pub const WbuCarWheelIndex_WBU_CAR_WHEEL_NB: WbuCarWheelIndex = 4;
pub type WbuCarWheelIndex = ::std::os::raw::c_uint;
unsafe extern "C" {
    pub fn wbu_car_init();
}
unsafe extern "C" {
    pub fn wbu_car_cleanup();
}
unsafe extern "C" {
    pub fn wbu_car_get_type() -> WbuCarType;
}
unsafe extern "C" {
    pub fn wbu_car_get_engine_type() -> WbuCarEngineType;
}
unsafe extern "C" {
    pub fn wbu_car_set_indicator_period(period: f64);
}
unsafe extern "C" {
    pub fn wbu_car_get_indicator_period() -> f64;
}
unsafe extern "C" {
    pub fn wbu_car_get_backwards_lights() -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wbu_car_get_brake_lights() -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wbu_car_get_track_front() -> f64;
}
unsafe extern "C" {
    pub fn wbu_car_get_track_rear() -> f64;
}
unsafe extern "C" {
    pub fn wbu_car_get_wheelbase() -> f64;
}
unsafe extern "C" {
    pub fn wbu_car_get_front_wheel_radius() -> f64;
}
unsafe extern "C" {
    pub fn wbu_car_get_rear_wheel_radius() -> f64;
}
unsafe extern "C" {
    pub fn wbu_car_get_wheel_encoder(wheel_index: WbuCarWheelIndex) -> f64;
}
unsafe extern "C" {
    pub fn wbu_car_get_wheel_speed(wheel_index: WbuCarWheelIndex) -> f64;
}
unsafe extern "C" {
    pub fn wbu_car_set_left_steering_angle(angle: f64);
}
unsafe extern "C" {
    pub fn wbu_car_set_right_steering_angle(angle: f64);
}
unsafe extern "C" {
    pub fn wbu_car_get_right_steering_angle() -> f64;
}
unsafe extern "C" {
    pub fn wbu_car_get_left_steering_angle() -> f64;
}
unsafe extern "C" {
    pub fn wbu_car_enable_limited_slip_differential(enable: ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn wbu_car_enable_indicator_auto_disabling(enable: ::std::os::raw::c_char);
}
pub const WbuDriverIndicatorState_OFF: WbuDriverIndicatorState = 0;
pub const WbuDriverIndicatorState_RIGHT: WbuDriverIndicatorState = 1;
pub const WbuDriverIndicatorState_LEFT: WbuDriverIndicatorState = 2;
pub type WbuDriverIndicatorState = ::std::os::raw::c_uint;
pub const WbuDriverControlMode_UNDEFINED_CONTROL_MODE: WbuDriverControlMode = -1;
pub const WbuDriverControlMode_SPEED: WbuDriverControlMode = 0;
pub const WbuDriverControlMode_TORQUE: WbuDriverControlMode = 1;
pub type WbuDriverControlMode = ::std::os::raw::c_int;
pub const WbuDriverWiperMode_DOWN: WbuDriverWiperMode = 0;
pub const WbuDriverWiperMode_SLOW: WbuDriverWiperMode = 1;
pub const WbuDriverWiperMode_NORMAL: WbuDriverWiperMode = 2;
pub const WbuDriverWiperMode_FAST: WbuDriverWiperMode = 3;
pub type WbuDriverWiperMode = ::std::os::raw::c_uint;
unsafe extern "C" {
    pub fn wbu_driver_initialization_is_possible() -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wbu_driver_init();
}
unsafe extern "C" {
    pub fn wbu_driver_cleanup();
}
unsafe extern "C" {
    pub fn wbu_driver_step() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wbu_driver_set_steering_angle(steering_angle: f64);
}
unsafe extern "C" {
    pub fn wbu_driver_get_steering_angle() -> f64;
}
unsafe extern "C" {
    pub fn wbu_driver_set_cruising_speed(speed: f64);
}
unsafe extern "C" {
    pub fn wbu_driver_get_target_cruising_speed() -> f64;
}
unsafe extern "C" {
    pub fn wbu_driver_get_current_speed() -> f64;
}
unsafe extern "C" {
    pub fn wbu_driver_set_throttle(throttle: f64);
}
unsafe extern "C" {
    pub fn wbu_driver_get_throttle() -> f64;
}
unsafe extern "C" {
    pub fn wbu_driver_set_brake_intensity(intensity: f64);
}
unsafe extern "C" {
    pub fn wbu_driver_get_brake_intensity() -> f64;
}
unsafe extern "C" {
    pub fn wbu_driver_set_indicator(state: WbuDriverIndicatorState);
}
unsafe extern "C" {
    pub fn wbu_driver_set_hazard_flashers(state: ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn wbu_driver_get_indicator() -> WbuDriverIndicatorState;
}
unsafe extern "C" {
    pub fn wbu_driver_get_hazard_flashers() -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wbu_driver_set_dipped_beams(state: ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn wbu_driver_set_antifog_lights(state: ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn wbu_driver_get_dipped_beams() -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wbu_driver_get_antifog_lights() -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wbu_driver_get_rpm() -> f64;
}
unsafe extern "C" {
    pub fn wbu_driver_get_gear() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wbu_driver_set_gear(gear: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn wbu_driver_get_gear_number() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wbu_driver_get_control_mode() -> WbuDriverControlMode;
}
unsafe extern "C" {
    pub fn wbu_driver_set_wiper_mode(mode: WbuDriverWiperMode);
}
unsafe extern "C" {
    pub fn wbu_driver_get_wiper_mode() -> WbuDriverWiperMode;
}
unsafe extern "C" {
    pub fn wbu_driver_set_brake(brake: f64);
}
unsafe extern "C" {
    pub fn wbu_driver_get_brake() -> f64;
}
pub use self::WbuDriverWiperMode as wbu_wipers_mode;
unsafe extern "C" {
    pub fn wbu_driver_set_wipers_mode(mode: wbu_wipers_mode);
}
unsafe extern "C" {
    pub fn wbu_driver_get_wipers_mode() -> wbu_wipers_mode;
}
unsafe extern "C" {
    pub fn wb_vacuum_gripper_enable_presence(
        tag: WbDeviceTag,
        sampling_period: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn wb_vacuum_gripper_disable_presence(tag: WbDeviceTag);
}
unsafe extern "C" {
    pub fn wb_vacuum_gripper_get_presence_sampling_period(
        tag: WbDeviceTag,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn wb_vacuum_gripper_get_presence(tag: WbDeviceTag) -> ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn wb_vacuum_gripper_turn_on(tag: WbDeviceTag);
}
unsafe extern "C" {
    pub fn wb_vacuum_gripper_turn_off(tag: WbDeviceTag);
}
unsafe extern "C" {
    pub fn wb_vacuum_gripper_is_on(tag: WbDeviceTag) -> ::std::os::raw::c_char;
}
